'use strict';
let expenses=[],editingId=null,busy=false,activeWorker=null,lastResilience=null,lastScenarioComparison=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=x=>Number.isFinite(x)?new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(x):'—';
const section=document.createElement('section');section.id='expenseSection';section.className='panel pad upgrade';
section.innerHTML=`<div class="upgrade-heading"><div><h2>Major, Irregular & Contingency Expenses</h2><p class="help">Keep occasional costs in the years they happen. All amounts are after-tax household spending needs in CAD.</p></div><button class="btn primary" id="addExpense">+ Add expense</button></div>
<details><summary>Existing 3.8 major purchase</summary><div class="formgrid" id="legacyExpenseFields"></div><p class="help">Preserved exactly: today’s dollars, inflation adjusted, funded using the household withdrawal strategy after Person A retires. Excluded from the new expense stress multiplier.</p></details>
<div class="formgrid"><div><label for="baseYear">Calendar year corresponding to current age</label><input id="baseYear" type="number" value="2026"><p class="help">For expense scheduling and calendar labels. The preserved tax model still starts from its 2026 basis.</p></div><div><label for="expenseStress">Selected irregular expense stress</label><select id="expenseStress"><option value="1">Normal</option><option value="1.25">+25%</option><option value="1.5">+50%</option><option value="2">+100%</option></select></div></div>
<label class="checkline"><input type="checkbox" id="includeContingencies"> Include random contingency expenses in Monte Carlo</label>
<p class="help">Probabilities and costs are your assumptions, not predictions. A 10% annual chance does not mean the expense happens every year. Historical / Hybrid mode uses planned expenses only.</p>
<div id="expenseList" aria-live="polite"></div>
</section>`;
const grid=document.querySelector('main>.grid');grid.before(section);
for(const id of ['lump','lumpAge'])$('legacyExpenseFields').append($(id).parentElement);
const storagePanel=document.createElement('section');storagePanel.className='panel pad upgrade';storagePanel.innerHTML=`<details><summary>Saved plans, scenarios & backups</summary><div class="buttonrow"><button id="savePlan" class="btn">Save on this device</button><button id="loadPlan" class="btn">Load saved plan</button><button id="exportPlan" class="btn">Export Plan JSON</button><label class="btn" for="importPlan">Import Plan JSON</label><input class="visually-hidden" type="file" id="importPlan" accept="application/json,.json"><button id="exportBackup" class="btn">Export all saved scenarios</button></div><div class="formgrid"><div><label for="scenarioName">Save a new scenario with this name</label><input id="scenarioName" placeholder="e.g. Conservative Home Maintenance" maxlength="100"></div><div class="buttonrow"><button id="saveScenario" class="btn">Save scenario</button><button id="compareScenarios" class="btn">Compare saved scenarios</button></div></div><div id="scenarioList"></div><p class="help">Copies are saved locally only. Export JSON to move a plan to another device or website. A saved scenario is a complete copy of the plan and its expenses.</p></details><p id="dataStatus" role="status">Local processing · no accounts · no uploads</p></section>`;section.before(storagePanel);
const resultPanel=document.createElement('section');resultPanel.className='panel pad upgrade';resultPanel.id='resiliencePanel';resultPanel.innerHTML=`<h2>Retirement Resilience</h2><div id="expenseMetrics" class="metric-grid"><p>Run a simulation to see expense and estate estimates.</p></div><div class="buttonrow"><button class="btn" id="compareResilience">Run contingency resilience & stress comparison</button><button class="btn" id="exportResults">Export Results CSV</button><button class="btn" id="printExpenses">Print / Save expense report as PDF</button></div><p class="help">Comparison uses one locked seed and the same market/inflation paths. It runs six sets of simulations. Success means 3.8’s full lifestyle success; flexible success is shown separately. Stress applies only to items marked “Include in stress test”.</p><div id="resilienceResults"></div><div id="scenarioResults"></div></section>`;
grid.querySelector('aside').nextElementSibling.prepend(resultPanel);
const timeline=document.createElement('section');timeline.className='panel pad upgrade';timeline.id='timelinePanel';timeline.innerHTML=`<h2>Retirement Spending Timeline</h2><p class="help" id="timelinePath">Select a representative path after running a simulation.</p><p class="help">Tap a year for its breakdown. Bars show requested regular spending, planned expenses, contingency expenses and modeled net tax. Actual delivered spending may be lower if funding fails.</p><div class="timeline-key"><span>● Regular</span><span>● Planned</span><span>● Contingency</span><span>● Tax</span></div><div id="timelineYears"></div><div id="yearBreakdown" aria-live="polite"></div><h2>Major & Irregular Expense Audit</h2><p class="help">New items are funded in list order after regular spending and the preserved 3.8 purchase. Tax shown is the incremental annual personal plus net corporate tax from funding that item; it can be negative after a modeled corporate refund. “Before/after” excludes subsequent reinvestment. The legacy purchase uses a same-year comparison with/without that purchase. No medical/dental expense credits are added to the preserved tax model.</p><div class="table-scroll" id="expenseAudit"></div></section>`;
document.querySelector('.rep-path').after(timeline);
const dialog=document.createElement('dialog');dialog.id='expenseDialog';dialog.innerHTML=`<form id="expenseForm"><div class="upgrade-heading"><h2>Add Retirement Expense</h2><button type="button" class="btn" id="closeExpense">Cancel</button></div><div class="formgrid">
<div><label for="eName">Expense name</label><input id="eName" required maxlength="100" placeholder="Replace car"></div>
<div><label for="eCategory">Category</label><select id="eCategory">${ExpenseEngine.categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div>
<div><label for="eType">Expense type</label><select id="eType"><option value="one-time">Known one-time expense</option><option value="recurring">Recurring capital replacement</option><option value="contingency">Random contingency</option></select></div>
<div><label for="eTiming">Schedule by</label><select id="eTiming"><option value="age">Person A age</option><option value="year">Calendar year</option></select></div>
<div><label for="eStart" id="eStartLabel">First occurrence / start age</label><input type="number" id="eStart" step="1" required></div>
<div id="endWrap"><label for="eEnd" id="eEndLabel">End age (inclusive)</label><input type="number" id="eEnd" step="1"></div>
<div id="intervalWrap"><label for="eInterval">Repeat every (years)</label><input id="eInterval" type="number" min="1" step="1" value="10"></div>
<div id="probWrap"><label for="eProbability">Annual probability (%)</label><input id="eProbability" type="number" min="0" max="100" step="0.1" value="10"></div>
<div id="amountModeWrap"><label for="eAmountMode">Expense amount</label><select id="eAmountMode"><option value="fixed">Fixed amount</option><option value="range">Uniform minimum–maximum range</option></select></div>
<div id="amountWrap"><label for="eAmount">Estimated cost (CAD)</label><input id="eAmount" type="number" min="0" step="any" value="50000"></div>
<div id="minWrap"><label for="eMin">Minimum cost (CAD)</label><input id="eMin" type="number" min="0" step="any" value="10000"></div>
<div id="maxWrap"><label for="eMax">Maximum cost (CAD)</label><input id="eMax" type="number" min="0" step="any" value="40000"></div>
<div><label for="eDollars">Cost expressed in</label><select id="eDollars"><option value="today">Today’s dollars</option><option value="future">Dollars at first occurrence</option></select></div>
<div><label for="eFunding">Funding source preference</label><select id="eFunding"><option value="plan">Follow household withdrawal strategy</option><option value="balanced">Non-registered first</option><option value="rrsp">RRSP/RRIF first</option><option value="corp">Corporate first</option><option value="tfsa">TFSA first</option></select><p class="help">Uses that 3.8 strategy’s normal fallback accounts if the preferred source is insufficient.</p></div>
</div><label class="checkline"><input id="eInflation" type="checkbox" checked>Inflation adjust</label><p class="help">Today’s dollars follow 3.8’s annual inflation timing, including inflation in the first modeled year. Future dollars are anchored at the first occurrence, then indexed for later replacements if selected.</p>
<div id="contingencyAdvanced"><details><summary>Optional contingency settings</summary><div class="formgrid"><div><label for="eLimit">Maximum occurrences (0 = no limit)</label><input id="eLimit" type="number" min="0" step="1" value="0"></div><div><label for="eGap">Minimum years between events</label><input id="eGap" type="number" min="0" step="1" value="0"></div></div><label class="checkline"><input id="eAgeProbability" type="checkbox">Change probability linearly with age</label><label for="eEndProbability">Annual probability at end age (%)</label><input id="eEndProbability" type="number" min="0" max="100" step="0.1" value="10"></details><p class="note">This does not mean you will spend this amount every year. During Monte Carlo simulations, Retirement Simulator randomly determines whether the expense occurs based on the probability you specify.</p></div>
<label for="eNotes">Notes</label><textarea id="eNotes" rows="2" maxlength="1000"></textarea><label class="checkline"><input id="eStress" type="checkbox" checked>Include in stress test</label><label class="checkline"><input id="eEnabled" type="checkbox" checked>Enabled</label><p id="expenseError" class="bad" role="alert"></p><button type="submit" class="btn primary">Save expense</button></form>`;document.body.append(dialog);
const originalControlIds=[...document.querySelectorAll('aside input[id],aside select[id],#legacyExpenseFields input[id]')].map(e=>e.id);
function readInputs(){return {...readLegacyInputs(),expenses:clone(expenses),baseYear:num('baseYear',2026),includeContingencies:$('includeContingencies').checked,expenseStress:num('expenseStress',1)};}
function captureUI(){const values={};for(const id of originalControlIds){const e=$(id);values[id]=e.type==='checkbox'?e.checked:e.value;}return {values,autoSeed:$('autoSeed').checked};}
function applyPlan(entry){const x=storageService.migratePlan(entry);SimulationAPI.check(x.plan);const p=x.plan;
 const map={planAge:'planAge',corp:'corp',corpACB:'corpACB',corpCDA:'corpCDA',corpRDTOH:'corpRDTOH',corpAdd:'corpAdd',corpAddUntil:'corpAddUntil',passiveCash:'passiveCash',passiveTaxable:'passiveTaxable',passiveStart:'passiveStart',passiveStop:'passiveStop',spend:'spend',lump:'lump',lumpAge:'lumpAge',sims:'sims',seed:'seed',histStart:'histStart',histEnd:'histEnd',strategy:'strategy',dist:'dist'};
 for(const [id,k] of Object.entries(map))$(id).value=p[k];
 for(const id of ['corpOwnerA','passiveOwnerA','essentialFloor','infStd','gmFI','gmCAD','gmUS','gmINTL','sdFI','sdCAD','sdUS','sdINTL','fee','corpFee','eqPersonal','eqCorp','maxDrop','maxGain','corpPassiveTax','corpRefundable','corpRefundRate'])$(id).value=p[id]*100;
 $('inflation').value=p.infMean*100;$('simMode').value=p.mode;$('household').value=p.couple?'couple':'single';$('useCDA').value=p.useCDA?'yes':'no';$('passiveIndex').value=p.passiveIndex?'yes':'no';for(const id of ['guardrails','pensionSplit'])$(id).checked=p[id];
 const personMap={Age:'age',Ret:'ret',RRSP:'rrsp',TFSA:'tfsa',TFSARoom:'tfsaRoom',NR:'nr',ACB:'acb',AddRRSP:'addRRSP',AddTFSA:'addTFSA',AddNR:'addNR',CPPAge:'cppAge',CPP65:'cpp65',OASAge:'oasAge',OAS65:'oas65',RRIFAge:'rrifAge'};
 for(const [prefix,person] of [['a',p.A],['b',p.B]])for(const [suffix,k] of Object.entries(personMap))$(prefix+suffix).value=person[k];
 // A stored UI snapshot preserves inactive spouse fields and exact decimal inputs.
 if(x.ui.values)for(const [id,value] of Object.entries(x.ui.values)){if(!originalControlIds.includes(id))continue;const e=$(id);if(e.type==='checkbox')e.checked=!!value;else e.value=value;}
 expenses=clone(p.expenses);$('baseYear').value=p.baseYear;$('expenseStress').value=p.expenseStress;$('includeContingencies').checked=p.includeContingencies;$('autoSeed').checked=false;$('seed').value=p.seed;for(const id of ['household','simMode'])$(id).dispatchEvent(new Event('change'));renderExpenses();invalidate();platformService.notify('Plan loaded. Seed locked for reproducibility. Run Simulation to update results.');}
function invalidate(){if(lastSimulationResult){$('dataStatus').textContent='Inputs changed. Displayed results still describe the last completed run.';}}
function expenseDefaults(){const age=Math.max(num('aRet'),num('aAge'));return {id:crypto.randomUUID?.()||'expense-'+Date.now(),name:'',category:'Vehicle',type:'one-time',timing:'age',start:age,end:Math.min(90,num('planAge')-1),interval:10,amount:50000,amountMode:'fixed',min:10000,max:40000,probability:.1,endProbability:.1,ageProbability:false,gap:0,maxOccurrences:0,dollars:'today',inflation:true,funding:'plan',notes:'',stress:true,enabled:true};}
const eMap={Name:'name',Category:'category',Type:'type',Timing:'timing',Start:'start',End:'end',Interval:'interval',Amount:'amount',AmountMode:'amountMode',Min:'min',Max:'max',Dollars:'dollars',Funding:'funding',Notes:'notes',Gap:'gap',Limit:'maxOccurrences'};
function editExpense(id=null){const e=id?expenses.find(x=>x.id===id):expenseDefaults();editingId=id||e.id;for(const [suffix,k] of Object.entries(eMap))$('e'+suffix).value=e[k];for(const [suffix,k] of [['Inflation','inflation'],['AgeProbability','ageProbability'],['Stress','stress'],['Enabled','enabled']])$('e'+suffix).checked=e[k];$('eProbability').value=e.probability*100;$('eEndProbability').value=e.endProbability*100;$('expenseError').textContent='';updateExpenseForm();dialog.showModal();$('eName').focus();}
function updateExpenseForm(){const type=$('eType').value,random=type==='contingency',range=random&&$('eAmountMode').value==='range';for(const [id,show] of Object.entries({endWrap:type!=='one-time',intervalWrap:type==='recurring',probWrap:random,amountModeWrap:random,minWrap:range,maxWrap:range,amountWrap:!range,contingencyAdvanced:random}))$(id).hidden=!show;
 if(random)$('eDollars').value='today';$('eDollars').disabled=random;const year=$('eTiming').value==='year';$('eStartLabel').textContent='First occurrence / start '+(year?'year':'age');$('eEndLabel').textContent='End '+(year?'year':'age')+' (inclusive)';}
function saveExpense(ev){ev.preventDefault();const e=expenseDefaults();e.id=editingId;for(const [suffix,k] of Object.entries(eMap)){const el=$('e'+suffix);e[k]=el.type==='number'?Number(el.value):el.value;}for(const [suffix,k] of [['Inflation','inflation'],['AgeProbability','ageProbability'],['Stress','stress'],['Enabled','enabled']])e[k]=$('e'+suffix).checked;e.probability=num('eProbability')/100;e.endProbability=num('eEndProbability')/100;if(e.type==='one-time')e.end=e.start;const errors=ExpenseEngine.validateExpenses({...readInputs(),expenses:[e]});if(errors.length){$('expenseError').textContent=errors.join(' ');return;}const index=expenses.findIndex(x=>x.id===e.id);if(index<0)expenses.push(e);else expenses[index]=e;renderExpenses();dialog.close();invalidate();}
function renderExpenses(){$('expenseList').innerHTML=expenses.length?expenses.map(e=>`<article class="expense-card"><div><strong>${esc(e.name)}</strong><p>${esc(e.category)} · ${esc(e.type)} · ${e.type==='contingency'&&e.amountMode==='range'?cash(e.min)+'–'+cash(e.max):cash(e.amount)} ${e.dollars==='today'?'today’s $':'first-occurrence $'}</p><p>${esc(e.timing==='age'?'Age':'Year')} ${e.start}${e.type!=='one-time'?'–'+e.end:''}${e.type==='recurring'?' · every '+e.interval+' years':''}${e.type==='contingency'?' · '+(e.probability*100).toFixed(1)+'% annual chance':''}${e.stress?' · stress selected':''}</p></div><div class="buttonrow"><label class="checkline"><input type="checkbox" data-toggle="${esc(e.id)}" ${e.enabled?'checked':''}>Enabled</label><button class="btn" data-edit="${esc(e.id)}">Edit</button><button class="btn" data-remove="${esc(e.id)}">Remove</button></div></article>`).join(''):'<p class="help">No additional expenses. Your existing 3.8 purchase remains available above.</p>';}
function setBusy(value){if(!value&&!busy)return;busy=value;for(const e of document.querySelectorAll('button,input,select,textarea')){if(e.closest('#expenseDialog'))continue;if(value){e.dataset.wasDisabled=e.disabled?'1':'0';e.disabled=true;}else{e.disabled=e.dataset.wasDisabled==='1';delete e.dataset.wasDisabled;}}$('cancelRun').disabled=!value;}
function progress(p,label){$('progressBar').style.width=(p*100).toFixed(0)+'%';$('statusText').textContent=label;}
function workerTask(action,plan,extra={}){return new Promise((resolve,reject)=>{let w;try{if((location.protocol==='file:'&&!globalThis.RETIREMENT_EMBEDDED_WORKER)||!globalThis.Worker)throw new Error('Use batched fallback');w=new Worker(globalThis.RETIREMENT_EMBEDDED_WORKER||'src/core/simulation-worker.js');}catch(e){const options={coarsePointer:true,onProgress:progress};const p=action==='allocations'?RetirementEngine.runAllocationComparison(plan,options):action==='resilience'?SimulationAPI.compareResilience(plan,options):action==='scenarios'?SimulationAPI.compareScenarios(extra.scenarios,extra.seed,options):SimulationAPI.runMonteCarlo(plan,options);p.then(resolve,reject);return;}activeWorker=w;w.onmessage=({data})=>{if(data.error){w.terminate();activeWorker=null;reject(new Error(data.error));}else if('result'in data){w.terminate();activeWorker=null;resolve(data.result);}else progress(data.progress,data.label);};w.onerror=e=>{w.terminate();activeWorker=null;reject(new Error(e.message||'Simulation worker could not load. Try reloading the application.'));};w.postMessage({action,plan,...extra});w.cancel=()=>{w.terminate();activeWorker=null;reject(new Error('Simulation cancelled. Your inputs are unchanged.'));};});}
function runSelectedSimulation(i){return workerTask('simulation',i);}
function runAllocationComparison(i){return workerTask('allocations',i);}
startSimulation=async function(){if(busy)return;if($('autoSeed').checked)$('seed').value=platformService.newSeed();const i=readInputs();try{SimulationAPI.check(i);}catch(e){alert(e.message);return;}$('seedHelp').textContent='Seed used: '+i.seed;setBusy(true);lastAllocationRows=null;lastResilience=null;lastScenarioComparison=null;$('resilienceResults').textContent='';$('scenarioResults').textContent='';try{const r=await runSelectedSimulation(i);lastSimulationResult=r;render(r);renderExpenseMetrics(r);if($('includeAllocation').checked){const rows=await runAllocationComparison(i);lastAllocationRows=rows;renderAllocationComparison(rows,i.mode);}else{$('allocTableBody').innerHTML='';$('allocSummary').textContent='Allocation comparison was not requested for this run.';}progress(1,'Complete');platformService.notify('Results complete. Seed: '+i.seed+'. Save or export your plan to retain these inputs.');}catch(e){platformService.notify(e.message);progress(0,'Stopped');}finally{setBusy(false);}};
const originalRenderPath=renderRepresentativePath;renderRepresentativePath=function(key='p50'){originalRenderPath(key);renderTimeline();};
function renderExpenseMetrics(r){const s=SimulationAPI.summary(r);const metrics=[['Full lifestyle failure',pct(s.failure)],['P10 / P25 ending estate',cash(s.p10)+' / '+cash(s.p25)],['Median ending estate',cash(s.p50)],['P75 / P90 ending estate',cash(s.p75)+' / '+cash(s.p90)],['Median depletion age in failed, depleted paths',s.depletionAge===null?'No such paths':s.depletionAge.toFixed(1)],['Lifetime irregular cost · mean / median / P90',s.meanIrregular===null?'Monte Carlo only':cash(s.meanIrregular)+' / '+cash(s.medianIrregular)+' / '+cash(s.p90Irregular)]];$('expenseMetrics').innerHTML=metrics.map(([name,value])=>`<div class="rep-stat"><div class="n">${esc(name)}</div><div class="v">${esc(value)}</div></div>`).join('')+'<p class="help">Estate = preserved 3.8 after-tax liquidation estimate. Irregular totals are requested costs, including the legacy purchase, in nominal lifetime dollars; they may exceed funded spending.</p>';}
function comparisonTable(rows){return `<div class="table-scroll"><table class="expense-table"><thead><tr>${['Scenario','Full success','Flexible success','Depletion','Median lifetime taxes','Median estate'].map(x=>'<th>'+x+'</th>').join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(r.name)}</th><td>${pct(r.full)}</td><td>${pct(r.flex)}</td><td>${pct(r.depletion)}</td><td>${cash(r.medianTax)}</td><td>${cash(r.p50)}</td></tr>`).join('')}</tbody></table></div>`;}
async function resilience(){if(busy)return;const i=readInputs();if(i.mode==='historical'){platformService.notify('Use Monte Carlo mode for the random contingency comparison.');return;}try{SimulationAPI.check(i);setBusy(true);const r=await workerTask('resilience',i);lastResilience={...r,plan:i};$('resilienceResults').innerHTML=`<h3>Contingency Resilience</h3><p>${pct(r.rows[1].full)} without random contingencies → ${pct(r.rows[2].full)} with contingencies. <strong>${r.contingencyDifference.toFixed(1)} percentage points</strong>. Seed ${r.seed}; ${i.sims.toLocaleString()} paths per row.</p>`+comparisonTable(r.rows);progress(1,'Comparison complete');}catch(e){platformService.notify(e.message);}finally{setBusy(false);}}
function sourceLabel(s){return typeof s==='string'?s:Object.entries(s||{}).filter(([,v])=>v>.01).map(([k,v])=>({rrspOut:'RRSP/RRIF',tfsaOut:'TFSA',nrOut:'Non-reg',corpOut:'Corp'})[k]+' '+cash(v)).join(', ')||'Existing after-tax cash';}
function selectedRows(){return representativePaths?.[representativeActive]?.path?.details||[];}
function yearItems(z){const a=z.expenseAudit||[];return {regular:z.guardedRecurring??z.plannedRecurring,planned:a.filter(e=>e.type!=='contingency').reduce((s,e)=>s+e.nominal,0),contingency:a.filter(e=>e.type==='contingency').reduce((s,e)=>s+e.nominal,0),tax:z.totalTax};}
function renderTimeline(){const rows=selectedRows();if(!rows.length)return;const r=lastSimulationResult;$('timelinePath').textContent=`${representativePaths[representativeActive].label} · seed ${r.i.seed} · actual expenses sampled in this path`;const max=Math.max(1,...rows.map(z=>Object.values(yearItems(z)).reduce((s,v)=>s+Math.max(0,v),0)));$('timelineYears').innerHTML=rows.map((z,k)=>{const items=yearItems(z);return `<button class="year-bar" data-year="${k}" aria-label="Age ${z.ageA}, cash requirement ${cash(z.totalRequired)}"><span>${z.ageA}</span><span class="bar-track">${Object.entries(items).map(([type,v])=>`<span class="bar-${type}" style="width:${Math.max(0,v)/max*100}%"></span>`).join('')}</span><span>${cash(z.totalRequired)}</span></button>`;}).join('');renderYear(Math.max(0,rows.findIndex(z=>z.expenseAudit?.length)));const events=rows.flatMap(z=>z.expenseAudit||[]);$('expenseAudit').innerHTML=events.length?`<table class="expense-table"><thead><tr>${['Year','Age','Expense','Category','Type','Today’s cost','Nominal cost','Funding / gross draws','Incremental tax','Portfolio before','Portfolio after','Expense funded'].map(x=>'<th>'+x+'</th>').join('')}</tr></thead><tbody>${events.map(e=>`<tr>${[e.year,e.age,e.name,e.category,e.type,cash(e.todayCost),cash(e.nominal),e.funding+' · '+sourceLabel(e.sources),cash(e.taxGenerated),cash(e.before),cash(e.after),cash(e.funded)].map(x=>'<td>'+esc(x)+'</td>').join('')}</tr>`).join('')}</tbody></table>`:'<p>No irregular expenses occur in this selected path.</p>';}
function renderYear(k){const z=selectedRows()[k];if(!z)return;const r=lastSimulationResult,year=z.calYear??r.i.baseYear+z.ageA-r.i.A.age;const items=[['Regular spending target',z.guardedRecurring??0],...(z.expenseAudit||[]).map(e=>[e.name,e.nominal]),['Personal income tax',z.personalTax],['Net corporate tax / refund',z.corpTax],['Total cash requirement',z.totalRequired],['Spending delivered',z.spending??0]];$('yearBreakdown').innerHTML=`<h3>Age ${z.ageA} · ${year}</h3><dl>${items.map(([n,v])=>'<dt>'+esc(n)+'</dt><dd>'+cash(v)+'</dd>').join('')}</dl><p class="help">Spending delivered excludes tax. Corporate tax is funded inside the corporation. Gross withdrawals can differ from cash requirements because of other income and reinvested surplus.</p>`;}
function renderScenarios(){try{const a=storageService.listScenarios();$('scenarioList').innerHTML=a.map(s=>`<div class="expense-card"><strong>${esc(s.name)}</strong><div class="buttonrow"><button class="btn" data-load-scenario="${esc(s.id)}">Load</button><button class="btn" data-delete-scenario="${esc(s.id)}">Delete</button></div></div>`).join('');}catch(e){platformService.notify(e.message);}}
function safe(fn){return async(...args)=>{try{await fn(...args);}catch(e){platformService.notify(e.message);}};}
function exportJSON(value,name){platformService.saveFile(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),name);}
function csvCell(v){let s=String(v??'');if(/^[=+@]/.test(s)||/^-[^\d]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function exportCSV(){if(!lastSimulationResult&&!lastResilience&&!lastScenarioComparison)throw new Error('Run a simulation or comparison first.');const a=[['Retirement Simulator 3.9','Values are simulation outcomes, CAD nominal unless labeled']];if(lastSimulationResult){a.push(['Main simulation seed',lastSimulationResult.i.seed],['Selected path',representativePaths[representativeActive].label],['Year','Age','Regular target','Planned expenses','Contingencies','Personal tax','Net corporate tax','Total cash required','Spending delivered','Ending assets']);for(const z of selectedRows()){const v=yearItems(z);a.push([z.calYear??lastSimulationResult.i.baseYear+z.ageA-lastSimulationResult.i.A.age,z.ageA,v.regular,v.planned,v.contingency,z.personalTax,z.corpTax,z.totalRequired,z.spending,z.end.total]);}a.push([],['Expense audit'],['Year','Age','Name','Category','Type','Today cost','Nominal cost','Funding sources','Incremental tax','Portfolio before','Portfolio after','Funded']);for(const z of selectedRows())for(const e of z.expenseAudit||[])a.push([e.year,e.age,e.name,e.category,e.type,e.todayCost,e.nominal,sourceLabel(e.sources),e.taxGenerated,e.before,e.after,e.funded]);}for(const [label,r] of [['Resilience',lastResilience],['Saved scenarios',lastScenarioComparison]])if(r){a.push([],[label,'Seed',r.seed],['Scenario','Full success %','Flexible success %','Depletion %','Median tax','Median estate']);for(const s of r.rows)a.push([s.name,s.full,s.flex,s.depletion,s.medianTax,s.p50]);}platformService.saveFile(new Blob(['\ufeff'+a.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'Retirement-Simulator-3.9-results.csv');}
function printExpenseReport(){if(!lastSimulationResult&&!lastResilience)throw new Error('Run the simulation or comparison first.');document.body.classList.add('printing-expenses');window.print();setTimeout(()=>document.body.classList.remove('printing-expenses'),1000);}
function initUpgrade(){const cancel=document.createElement('button');cancel.id='cancelRun';cancel.className='btn';cancel.textContent='Cancel run';cancel.disabled=true;document.querySelector('header .actions').append(cancel);cancel.onclick=()=>{if(activeWorker)activeWorker.cancel();else platformService.notify('Local-file fallback is batched but cannot be cancelled. Reload to stop.');};
const seedBtn=document.createElement('button');seedBtn.className='btn';seedBtn.textContent='Generate New Seed';seedBtn.onclick=()=>{$('seed').value=platformService.newSeed();$('autoSeed').checked=false;$('seedHelp').textContent='Seed locked: '+$('seed').value;invalidate();};$('seedHelp').after(seedBtn);
const alloc=document.createElement('label');alloc.className='checkline';alloc.innerHTML='<input id="includeAllocation" type="checkbox" checked>Run the existing five-allocation comparison';$('leftAdvanced').append(alloc);
$('addExpense').onclick=()=>editExpense();$('closeExpense').onclick=()=>dialog.close();$('expenseForm').onsubmit=saveExpense;
for(const id of ['eType','eAmountMode'])$(id).onchange=updateExpenseForm;$('eTiming').onchange=()=>{const shift=num('baseYear')-num('aAge'),d=$('eTiming').value==='year'?shift:-shift;$('eStart').value=num('eStart')+d;$('eEnd').value=num('eEnd')+d;updateExpenseForm();};
$('expenseList').onclick=e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.edit)editExpense(b.dataset.edit);if(b.dataset.remove&&confirm('Remove this expense from the current plan? Saved scenarios stay available.')){expenses=expenses.filter(x=>x.id!==b.dataset.remove);renderExpenses();invalidate();}};
$('expenseList').onchange=e=>{const id=e.target.dataset.toggle;if(id){expenses.find(x=>x.id===id).enabled=e.target.checked;invalidate();}};
$('savePlan').onclick=safe(()=>{const p=readInputs();SimulationAPI.check(p);storageService.savePlan(p,captureUI());platformService.notify('Plan saved on this device.');});
$('loadPlan').onclick=safe(()=>{const p=storageService.loadPlan();if(!p)throw new Error('No plan has been saved on this device yet.');applyPlan(p);});
$('exportPlan').onclick=safe(()=>{const p=readInputs();SimulationAPI.check(p);exportJSON(storageService.envelope(p,captureUI()),'Retirement-Simulator-3.9-plan.json');});
$('importPlan').onchange=safe(async e=>{const file=e.target.files[0];if(!file)return;const d=JSON.parse(await platformService.readFile(file));if(Array.isArray(d.scenarios)){const staged=d.scenarios.map(s=>({...s,...storageService.migratePlan(s)}));for(const s of staged)SimulationAPI.check(s.plan);for(const s of staged)storageService.saveScenario(s.name,s.plan,s.ui);if(d.current)applyPlan(d.current);renderScenarios();platformService.notify('Backup imported as new scenario copies. Existing scenarios retained.');}else applyPlan(d);e.target.value='';});
$('exportBackup').onclick=safe(()=>platformService.saveFile(new Blob([storageService.backup()],{type:'application/json'}),'Retirement-Simulator-3.9-backup.json'));
$('saveScenario').onclick=safe(()=>{const p=readInputs();SimulationAPI.check(p);storageService.saveScenario($('scenarioName').value,p,captureUI());renderScenarios();platformService.notify('Scenario saved.');});
$('scenarioList').onclick=safe(e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.loadScenario)applyPlan(storageService.listScenarios().find(s=>s.id===b.dataset.loadScenario));if(b.dataset.deleteScenario&&confirm('Delete this saved scenario?')){storageService.deleteScenario(b.dataset.deleteScenario);renderScenarios();}});
$('compareScenarios').onclick=safe(async()=>{const a=storageService.listScenarios();if(a.length<2)throw new Error('Save at least two scenarios to compare.');if(busy)return;setBusy(true);try{const seed=num('seed'),r=await workerTask('scenarios',null,{scenarios:a,seed});lastScenarioComparison=r;$('scenarioResults').innerHTML='<h3>Saved scenario comparison · seed '+seed+'</h3>'+comparisonTable(r.rows);progress(1,'Scenarios compared');}finally{setBusy(false);}});
$('compareResilience').onclick=resilience;$('timelineYears').onclick=e=>{const b=e.target.closest('[data-year]');if(b)renderYear(Number(b.dataset.year));};$('exportResults').onclick=safe(exportCSV);$('printExpenses').onclick=safe(printExpenseReport);
// Preserve baseline controls and improve label associations / mobile keyboards.
for(const input of document.querySelectorAll('input[type=number]'))input.inputMode='decimal';for(const el of document.querySelectorAll('aside input[id],aside select[id]')){const label=el.parentElement.querySelector('label');if(label&&!label.htmlFor)label.htmlFor=el.id;}
 document.addEventListener('change',e=>{if(e.target.matches('input,select,textarea'))invalidate();});renderExpenses();renderScenarios();bindUI();setupPWA();}
async function setupPWA(){if(!globalThis.RETIREMENT_STANDALONE&&'serviceWorker'in navigator&&location.protocol!=='file:'){try{const reg=await navigator.serviceWorker.register('./sw.js');const notify=worker=>{if(!worker)return;const btn=document.createElement('button');btn.className='btn';btn.textContent='Update available — reload';btn.onclick=safe(()=>{const p=readInputs();SimulationAPI.check(p);storageService.savePlan(p,captureUI());sessionStorage.setItem('retirement-restore-after-update','1');worker.postMessage({type:'SKIP_WAITING'});});document.querySelector('header .actions').append(btn);};notify(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)notify(w);});});let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloading&&sessionStorage.getItem('retirement-restore-after-update')){reloading=true;location.reload();}});if(sessionStorage.getItem('retirement-restore-after-update')){const p=storageService.loadPlan();if(p)applyPlan(p);sessionStorage.removeItem('retirement-restore-after-update');}}catch(e){platformService.notify('Offline installation is not available here. Calculations still work while the page is open.');}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();const b=document.createElement('button');b.className='btn';b.textContent='Install app';b.onclick=()=>e.prompt();document.querySelector('header .actions').append(b);});}
initUpgrade();

function expenseReportPages(){const lines=[];if(lastSimulationResult){const r=lastSimulationResult,s=SimulationAPI.summary(r);lines.push('MAIN SIMULATION | seed '+r.i.seed+' | '+r.i.sims+' paths',`Full success ${pct(r.full)} | Flexible ${pct(r.flex)} | Failure ${pct(s.failure)} | Depletion ${pct(s.depletion)}`,`Ending estate P10 ${cash(s.p10)} | P25 ${cash(s.p25)} | Median ${cash(s.p50)}`,`Ending estate P75 ${cash(s.p75)} | P90 ${cash(s.p90)} | Median lifetime tax ${cash(s.medianTax)}`,`Irregular requested lifetime costs: mean ${cash(s.meanIrregular)}, median ${cash(s.medianIrregular)}, P90 ${cash(s.p90Irregular)}`,'','SELECTED PATH SPENDING TIMELINE | '+representativePaths[representativeActive].label,'Amounts in CAD nominal. Cash required includes personal and net corporate tax.');for(const z of selectedRows()){const v=yearItems(z),year=z.calYear??r.i.baseYear+z.ageA-r.i.A.age;lines.push(`${year} | Age ${z.ageA} | Regular ${cash(v.regular)} | Planned ${cash(v.planned)} | Contingency ${cash(v.contingency)} | Tax ${cash(v.tax)} | Total ${cash(z.totalRequired)}`);}lines.push('','MAJOR & IRREGULAR EXPENSE AUDIT','New items: incremental funding after regular spending and legacy purchase.','Legacy purchase: same-year marginal comparison with/without the purchase.');for(const z of selectedRows())for(const e of z.expenseAudit||[]){lines.push(`${e.year} | Age ${e.age} | ${e.name} | ${e.category} | ${e.type}`,`Today ${cash(e.todayCost)} | Nominal ${cash(e.nominal)} | Funded ${cash(e.funded)} | Added net tax ${cash(e.taxGenerated)}`,`Portfolio before ${cash(e.before)} | After ${cash(e.after)} | Preference ${e.funding}`,`Gross draws: ${sourceLabel(e.sources)}`);}}
for(const [name,r] of [['CONTINGENCY RESILIENCE & STRESS',lastResilience],['SAVED SCENARIO COMPARISON',lastScenarioComparison]])if(r){lines.push('',name+' | seed '+r.seed);for(const z of r.rows)lines.push(`${z.name} | Full ${pct(z.full)} | Flexible ${pct(z.flex)} | Depletion ${pct(z.depletion)} | Median tax ${cash(z.medianTax)} | Estate ${cash(z.p50)}`);}
lines.push('','Expense probabilities and costs are assumptions, not forecasts.','Stress affects selected new expenses only. The legacy purchase is excluded.','The preserved 3.8 tax model includes no medical/dental expense credits.');const pages=[];let page=newPdfPage(),y=175;const start=()=>{pageTitle(page.x,'Major, Irregular & Contingency Expense Report','Retirement Simulator 3.9 | Local simulation outcomes');page.x.fillStyle='#243e58';page.x.font='17px Arial';};start();for(const line of lines){if(y>1080){pageFooter(page.x);pages.push(page.c);page=newPdfPage();y=175;start();}y=wrapCanvasText(page.x,line||' ',58,y,1460,26)+9;}pageFooter(page.x);pages.push(page.c);return pages;}
