/* Replace these adapters when adding native Capacitor plugins. Never used by calculations. */
(function(global){'use strict';
const KEY='retirement-simulator:3.9';let adapter={get:key=>localStorage.getItem(key),set:(key,value)=>localStorage.setItem(key,value)};
function migratePlan(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('This file is not a retirement plan.');if(input.schemaVersion&&!['3.8','3.9'].includes(String(input.schemaVersion)))throw new Error('Unsupported schema version; the original file has not been changed.');const plan=JSON.parse(JSON.stringify(input.plan??input.i??input));if(!plan.A||!plan.B||!Number.isFinite(plan.A.age)||!Number.isFinite(plan.spend)||!Number.isFinite(plan.lump))throw new Error('Expected a complete simulator plan object, including A, B, spend, lump and lumpAge. HTML files are not JSON plans.');
const source=input.sourceVersion??(input.schemaVersion==='3.9'?'3.9':'3.8');plan.expenses??=[];plan.includeContingencies??=false;plan.expenseStress??=1;plan.baseYear??=2026;
return {schemaVersion:'3.9',sourceVersion:source,plan,ui:input.ui||{}};}
function envelope(plan,ui={}){return {schemaVersion:'3.9',sourceVersion:'3.8',plan:JSON.parse(JSON.stringify(plan)),ui};}
function read(){const raw=adapter.get(KEY);if(!raw)return {schemaVersion:'3.9',scenarios:[]};let d;try{d=JSON.parse(raw);}catch(e){throw new Error('Saved data could not be read; export a backup before replacing it.');}if(d.schemaVersion!=='3.9'||!Array.isArray(d.scenarios))throw new Error('Unrecognized saved-data format; it has been left untouched.');return d;}
function write(d){try{adapter.set(KEY,JSON.stringify(d));}catch(e){throw new Error('Could not save on this device. Export Plan JSON to keep a copy.');}}
global.storageService={migratePlan,envelope,setAdapter:a=>{adapter=a;},loadPlan(){const d=read();return d.current?migratePlan(d.current):null;},savePlan(plan,ui={}){const d=read();d.current=envelope(plan,ui);write(d);},listScenarios:()=>read().scenarios,saveScenario(name,plan,ui={}){if(!name?.trim())throw new Error('Enter a scenario name.');const d=read(),id=global.crypto?.randomUUID?.()||String(Date.now())+'-'+Math.random().toString(36).slice(2);d.scenarios.push({id,name:name.trim(),...envelope(plan,ui)});write(d);return id;},deleteScenario(id){const d=read();d.scenarios=d.scenarios.filter(s=>s.id!==id);write(d);},backup:()=>JSON.stringify(read(),null,2)};
function saveFile(blob,filename){const url=URL.createObjectURL(blob),ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);if(blob.type==='application/pdf'&&ios){const w=window.open(url,'_blank');if(!w)location.href=url;}else{const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();}setTimeout(()=>URL.revokeObjectURL(url),60000);}
global.platformService={saveFile,readFile:file=>file.text(),share:async(blob,name)=>{const f=new File([blob],name,{type:blob.type});if(navigator.canShare?.({files:[f]}))return navigator.share({files:[f]});saveFile(blob,name);},notify:message=>{const el=document.getElementById('dataStatus');if(el)el.textContent=message;},newSeed:()=>{const a=new Uint32Array(1);global.crypto.getRandomValues(a);return a[0]||1;}};
})(globalThis);
